[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py"]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "setup.cfg", "requirements.txt", "Pipfile", "pyrightconfig.json"]
comment-token = "#"
language-server = { command = "pyright-langserver", args = ["--stdio"] }
# TODO: pyls needs utf-8 offsets
indent = { tab-width = 4, unit = "    " }
