require("navin.plugins")
require("navin.lsp-config")
require("navin.lsp-wrapper")
require("navin.telescope-config")
require("navin.treesitter-config")
require("navin.lualine-config")
require("navin.lua-ls")
