require("navin.lsp-config")
require("navin.lsp-wrapper")
require("navin.compe-config")
require("navin.telescope-config")
require("navin.treesitter-config")
require("navin.lualine-config")
require("navin.bufferline-config")
require("navin.lua-ls")
