#!/bin/bash
# Opens a Notes file and creates a header if file does not exist.

# Usage
if [ $# -eq 3 ]; then
	export TASK_DESCRIPTION=$2
	export TASK_UUID=$3
	task_description_array=($TASK_DESCRIPTION)
	# if [ - ]; then
	#
	# fi

	content=$(cat jiranote_template.md | envsubst)
	if [ ! -e $1 ]; then
		echo "#content" > $1
	fi
	$EDITOR $1
else
	echo "Usage: $0 <file-path> <description> <uuid>"
fi
