#! /bin/sh


# autostart
killall sxhkd
sxhkd &

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
if [ -x $HOME/Projects/scripts/monitor/dual_monitor ];then
    $HOME/Projects/scripts/monitor/dual_monitor
fi

$HOME/.config/polybar/launch.sh
xmodmap $HOME/.config/.xmodmaprc
killall nitrogen
nitrogen --restore &
killall picom
picom &

# monitor workspace
bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 0

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

###---Monitor And Desktop Settings----###
bspc config top_padding 22
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 5

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

###---Coloring---###
bspc config normal_border_color	"#1e282d'"
bspc config active_border_color	"#1e282d'"
bspc config focused_border_color "#c4c7d1'"
bspc config presel_feedback_color	"#ffffff"
bspc config urgent_border_color "#eb606b'"

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
