#! /bin/sh


killall sxhkd
sxhkd &

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
dual_monitor

# monitor workspace
bspc monitor HDMI1 -d 1 2 3 4 5
bspc monitor eDP1 -d 6 7 8 9 0

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 23
bspc config border_width 1
bspc config window_gap 1

bspc config focus_follows_pointer false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

###---Coloring---###
bspc config normal_border_color	"#1e282d'"
bspc config active_border_color	"#1e282d'"
bspc config focused_border_color "#c4c7d1'"
bspc config presel_feedback_color	"#ffffff"
bspc config urgent_border_color "#eb606b'"

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a 'firefox' desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a '*:*:Desktop — Plasma' state=floating border=off
bspc rule -a Plasma state=floating border=off
bspc rule -a plasma-desktop state=floating border=off
bspc rule -a win7 state=floating border=off
bspc rule -a krunner state=floating border=off
bspc rule -a Kmix state=floating border=off
bspc rule -a Klipper state=floating border=off
bspc rule -a Plasmoidviewer state=floating border=off
bspc rule -a plasmashell state=floating border=off focus=off manage=off center=off
