#!/usr/bin/env bash
"$HOME"/.screenlayout/dual-screen.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
setxkbmap -option ctrl:nocaps &
xset r rate 300 40 &
xfce4-power-manager --daemon &
timewarrior-web.py &
